"""users

Revision ID: f6b9ad2f11bf
Revises:
Create Date: 2025-05-24 12:07:50.081077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6b9ad2f11bf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("gender", sa.Enum("male", "female", name="gender"), nullable=False),
        sa.Column("first_name", sa.String(length=320), nullable=False),
        sa.Column("last_name", sa.String(length=320), nullable=False),
        sa.Column("email", sa.String(length=1024), nullable=False),
        sa.Column("phone_number", sa.String(length=320), nullable=False),
        sa.Column("address", sa.String(length=1024), nullable=False),
        sa.Column("photo_url", sa.String(length=1024), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_user")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.execute('DROP TYPE gender')
    # ### end Alembic commands ###
